### ISSUE TITLE
[dosbox emu]: execute "CLICK TO START" ONLY AFTER COMPLETE FILE IS DOWNLOADED

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-central#12]

**Comment by dnelband** [comment]
emulator start is now bound to file status "is_downloaded" provided by the zeronet api and will start when is true.

**Comment by dnelband** [comment]
ok updated, now:
1 - before emulator starts, ajax call to the file ("downloading ...")
2 - when file is readyState = 4 (file is found) then launch emulator but ONLY if according to the zeronet site_file.is_downloaded = 1 (i.e double check if file is there - ajax & zeronet)
3 - emulator downloads js-dos specific files & extracts zip ("extracing ...")
4 - emulator is ready ("running") 
is this right?

**Comment by dnelband** [comment]
btw emulator ready + file downloaded doesnt mean that the file would play, it means just that the file is there and the emulator has mounted it. when emualtor shows (Z:/) and nothing happens it means that the executable file (EXE / COM) isnt working or wasnt specified

**Comment by haschimoto** [comment]
error:
Uncaught TypeError: Cannot read property 'is_downloaded' of undefined
    at Dosbox.onrun (dosbox.directive.js:36)
    at func (<anonymous>:132:27)
