### ISSUE TITLE
[view]: channel link (like on "video view" page) should be linked back to remote master site view instead of the channel itself

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-central#16]

**Comment by dnelband** [comment]
done. clicking on filename in the user channel file list will link to the item view in the master site. clicking on the pencil icon will link to the edit area inside the user-channel area

**Comment by haschimoto** [comment]
Is the link in the view.html also fixex?

**Comment by haschimoto** [comment]
please label anything done with green "done" label.
