### ISSUE TITLE
view.html: # peers should always be file peers, not channel

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-central#21]

**Comment by siyuandong** [comment]
view.html has already real file peers from Page.cmd("optionalFileList").

**Comment by haschimoto** [comment]
Have you even TESTED this or just saying this "per thumb"?? Just click a
video and it shows channel peers...

**Comment by siyuandong** [comment]
I admit I debuged and tested only on games.. yes, video use different view code.  apparently shows channel peers. i will fix it.
