### ISSUE TITLE
user: missing "edit" and "delete" buttons at end of each file

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-central#23]
![snap 2017-01-19 at 16 38 03](https://cloud.githubusercontent.com/assets/20817185/22113185/bd2c03b4-de65-11e6-853e-fbe31cd7449e.png)

**Comment by siyuandong** [comment]
I have the buttons... maybe is fixed already... otherwise pls post the channel address here.

**Comment by haschimoto** [comment]
you have it fixed inside master showing the channel under "user"?
Can you post a screenshot here??
Do we need to fix each channel to make it work or wouldnt it now be the same for all in master/user?

**Comment by siyuandong** [comment]
![ssifs](https://cloud.githubusercontent.com/assets/1433312/22146618/90676d50-df05-11e6-83e4-f86574539968.png)

they would be all the same.

**Comment by siyuandong** [comment]
"edit" & "delete" Btn only shown when user the owner of the site is. 
please check if "This is my site" checked or not.
