### ISSUE TITLE
add CPC Emulator and Games Filetype

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-central#7]
Here is a CPC JS Emulator:
http://roland.retrolandia.net/

One other emulator on the same site:
http://jbacteria.retrolandia.net/

Part of:
http://retrolandia.net/

QAOP:
http://torinak.com/qaop/games

NOTES:
Code: https://sourceforge.net/p/emuscriptoria/code/HEAD/tree/

In use:
http://www.juegotk.com/emuladores/roland/index.html?Arkanoid.dsk/run%22arkanoid

The main site is here, but not all games when started via "Jugar Online" work:
http://www.juegotk.com/emulador-online/2-8/amstrad-cpc464.html

There is also an old Emulator and some games (dont use this):
https://bit.no.com:43110/19VKLy7AAJaKfXb4sdE8YQjRaUcYfBXdis

**Comment by haschimoto** [comment]
use this logo for cpc game filetype
![amstrad-cpc](https://cloud.githubusercontent.com/assets/20817185/21720498/ceba84d0-d423-11e6-8b45-4d6089da80e6.jpg)

**Comment by haschimoto** [comment]
http://127.0.01:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/merged-IFS/1FHtDQ8i5NFFeuo7Fux6TeLpwmmeUGvdc8/uploads/games/fruity_frank.sna.

Error: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 404.

**Comment by haschimoto** [comment]
Here is another JS Emulator:
http://roland.retrolandia.net/

Lets try to change to this.

**Comment by haschimoto** [comment]
Code: https://sourceforge.net/p/emuscriptoria/code/HEAD/tree/

**Comment by dnelband** [comment]
http://127.0.0.1:43110/1NS2RPpGtkqV4YZH1Ymx4CPm5ogDKXzyKK - still not working, and looks like it needs php

**Comment by haschimoto** [comment]
I found this:
http://www.juegotk.com/emuladores/roland/index.html?Arkanoid.dsk/run%22arkanoid
